2013/03/06 21:17:23 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1130] Host '42.114.6.227' is not allowed to connect to this MySQL server' in E:\xampp\htdocs\yiiframework\framework\db\CDbConnection.php:381
Stack trace:
#0 E:\xampp\htdocs\yiiframework\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 E:\xampp\htdocs\yiiframework\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 E:\xampp\htdocs\yiiframework\framework\base\CModule.php(387): CDbConnection->init()
#3 E:\xampp\htdocs\yiiframework\framework\base\CModule.php(103): CModule->getComponent('db')
#4 E:\xampp\htdocs\yiiframework\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 E:\xampp\htdocs\yiiframework\framework\web\CFormModel.php(39): ModelCode->init()
#6 E:\xampp\htdocs\yiiframework\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 E:\xampp\htdocs\yiiframework\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 E:\xampp\htdocs\yiiframework\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 E:\xampp\htdocs\yiiframework\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 E:\xampp\htdocs\yiiframework\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 E:\xampp\htdocs\yiiframework\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 E:\xampp\htdocs\yiiframework\framework\web\CWebApplication.php(282): CController->run('')
#13 E:\xampp\htdocs\yiiframework\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model')
#14 E:\xampp\htdocs\yiiframework\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 E:\xampp\htdocs\website\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/website/index.php?r=gii/model
HTTP_REFERER=http://localhost/website/index.php?r=gii/model
---
2013/03/06 21:17:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1130] Host '42.114.6.227' is not allowed to connect to this MySQL server' in E:\xampp\htdocs\yiiframework\framework\db\CDbConnection.php:381
Stack trace:
#0 E:\xampp\htdocs\yiiframework\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 E:\xampp\htdocs\yiiframework\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 E:\xampp\htdocs\yiiframework\framework\base\CModule.php(387): CDbConnection->init()
#3 E:\xampp\htdocs\yiiframework\framework\base\CModule.php(103): CModule->getComponent('db')
#4 E:\xampp\htdocs\yiiframework\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 E:\xampp\htdocs\yiiframework\framework\web\CFormModel.php(39): ModelCode->init()
#6 E:\xampp\htdocs\yiiframework\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 E:\xampp\htdocs\yiiframework\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 E:\xampp\htdocs\yiiframework\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 E:\xampp\htdocs\yiiframework\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 E:\xampp\htdocs\yiiframework\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 E:\xampp\htdocs\yiiframework\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 E:\xampp\htdocs\yiiframework\framework\web\CWebApplication.php(282): CController->run('')
#13 E:\xampp\htdocs\yiiframework\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model')
#14 E:\xampp\htdocs\yiiframework\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 E:\xampp\htdocs\website\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/website/index.php?r=gii/model
HTTP_REFERER=http://localhost/website/index.php?r=gii/model
---
2013/03/06 21:22:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users".' in E:\xampp\htdocs\yiiframework\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\yiiframework\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#1 E:\xampp\htdocs\yiiframework\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 E:\xampp\htdocs\website\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/website/index.php?r=users
---
2013/03/07 03:45:59 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /opt/lampp/htdocs/yiiframework/framework/gii/GiiModule.php:168
Stack trace:
#0 /opt/lampp/htdocs/yiiframework/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /opt/lampp/htdocs/yiiframework/framework/web/CWebApplication.php(282): CController->run('')
#2 /opt/lampp/htdocs/yiiframework/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /opt/lampp/htdocs/yiiframework/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /opt/lampp/htdocs/vncweb/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/vncweb/index.php?r=gii
---
2013/03/07 10:17:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "news".' in /opt/lampp/htdocs/yiiframework/framework/web/CController.php:483
Stack trace:
#0 /opt/lampp/htdocs/yiiframework/framework/web/CController.php(270): CController->missingAction('news')
#1 /opt/lampp/htdocs/yiiframework/framework/web/CWebApplication.php(282): CController->run('news')
#2 /opt/lampp/htdocs/yiiframework/framework/web/CWebApplication.php(141): CWebApplication->runController('site/news')
#3 /opt/lampp/htdocs/yiiframework/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /opt/lampp/htdocs/vncweb/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/vncweb/index.php?r=site/news
---
2013/03/07 10:17:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "news".' in /opt/lampp/htdocs/yiiframework/framework/web/CController.php:483
Stack trace:
#0 /opt/lampp/htdocs/yiiframework/framework/web/CController.php(270): CController->missingAction('news')
#1 /opt/lampp/htdocs/yiiframework/framework/web/CWebApplication.php(282): CController->run('news')
#2 /opt/lampp/htdocs/yiiframework/framework/web/CWebApplication.php(141): CWebApplication->runController('site/news')
#3 /opt/lampp/htdocs/yiiframework/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /opt/lampp/htdocs/vncweb/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/vncweb/index.php?r=site/news
---
2013/03/07 10:18:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "news".' in /opt/lampp/htdocs/yiiframework/framework/web/CController.php:483
Stack trace:
#0 /opt/lampp/htdocs/yiiframework/framework/web/CController.php(270): CController->missingAction('news')
#1 /opt/lampp/htdocs/yiiframework/framework/web/CWebApplication.php(282): CController->run('news')
#2 /opt/lampp/htdocs/yiiframework/framework/web/CWebApplication.php(141): CWebApplication->runController('site/news')
#3 /opt/lampp/htdocs/yiiframework/framework/base/CApplication.php(169): CWebApplication->processRequest()
#4 /opt/lampp/htdocs/vncweb/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/vncweb/index.php?r=site/news
---
